### ISSUE TITLE
Suggestion: Use "expose" instead of "ports" for DDEV

### ISSUE THREAD

**Issue by mandrasch** [nystudio107/craft-vite#38]
Hey, 

I found your example configuration for DDEV in https://nystudio107.com/docs/vite/#using-ddev while research for DDEV + vite.

Just wanted to let you know that I had a quick discussion with [Randy Fay](https://github.com/rfay) about the docker-compose file:

He suggested using `expose` instead of `ports`:

> You just want `expose`, not `ports` if you're going to put it on port 3000, because with your current setup ddev-router is also going to try to use port 3000
> _Originally posted by rfay in https://github.com/torenware/ddev-viteserve/issues/2#issuecomment-1184472413_

(Official docs on this: https://ddev.readthedocs.io/en/stable/users/extend/custom-compose-files/#docker-composeyaml-examples, ports uses host computer, expose uses DDEV router instead)

Disclaimer: I'm not a craft dev myself, just strongly interested in vite + DDEV (https://github.com/mandrasch/ddev-addon-simple-vite). 

Much success with your project and best regards,
Matthias

**Comment by khalwat** [comment]
@johndwells thoughts?

**Comment by johndwells** [comment]
@khalwat @mandrasch Interesting. The premise seems right, I'd just like to test this with real values to verify the approach.

**Comment by johndwells** [comment]
Based on the comment @mandrasch linked in his original, this indeed seems to work just fine:

```
# ./ddev/docker-compose.vite.yaml
version: '3.6'
services:
  web:
    expose:
      - '3000'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```
