### ISSUE TITLE
400 Bad Request after starting vite dev

### ISSUE THREAD

**Issue by williamExitable** [nystudio107/craft-vite#50]
### Question
I get a 400 Bad Request error when I open the URL http://localhost:3000 after running `ddev npm run dev` 

**docker-compose.vite.yaml**
```
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE services
# to expose port 3000 of DDEV's web container.
version: '3.6'
services:
  web:
    # ports are a list of exposed *container* ports
    ports:
      - "3000"
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```

**vite.config.js**
`  server: {
    host: '0.0.0.0',
    port: 3000,
    strictPort: true,
  },`

**package.json**
`  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },`
