### ISSUE TITLE
vite dev server not coming through to templates

### ISSUE THREAD

**Issue by joepagan** [nystudio107/craft-vite#9]
### Question

Hey, not sure if I'm doing something wrong though I cannot get vite dev server (`/@vite/client.js`) to come through to templates.

### Additional context

[As you have highlighted here](https://github.com/craftcms/nitro/issues/360#issuecomment-846725518), the php container cannot access the vite container on `localhost:3000` so needs a different URL to check, like your comment I setup:
```
// VITE_DEV_SERVER_INTERNAL=http://vite:3000/
'devServerInternal' => App::env('VITE_DEV_SERVER_INTERNAL'),
    'checkDevServer' => true,
```

When I run xdebug, I can see content in [this `fetch` method]()https://github.com/nystudio107/craft-plugin-vite/blob/v1/src/services/ViteService.php#L366 it appears to be getting the contents of `client.js` file so it should be coming through without me needing to do anything else right?

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/2337910/123561702-f086ba80-d7a1-11eb-8e7e-a8883b61d131.png">

Thanks for your work on this.

**Comment by khalwat** [comment]
I can't answer your question without knowing your local dev environment, and also I'd need to see your code where you try to include the script.

But I would turn `checkDevServer` off:
```
'devServerInternal' => App::env('VITE_DEV_SERVER_INTERNAL'),
'checkDevServer' => false,
```

And try to get it working without the automatic devServer fallback first.

**Comment by joepagan** [comment]
With `'checkDevServer' => false,` my `.ts` file is referenced in the template at `<script type="module" src="http://localhost:3000/src/js/home.ts"></script>`, though no `client.js` comes through still unfortunately.

Appreciate this is difficult for you to advise much further without more dev env info. Let me know if you need anything else.

index.twig:

```
...
<body class="ltr">
home
 {{ craft.vite.script("/src/js/home.ts") }}
</body>
...
```

here is my docker-compose.yml:

```yml
version: "2.2"
services:
  appdata:
    build:
      context: ./
      dockerfile: ./docker/development/config/app.dockerfile
    volumes:
      - ./:/var/www/site
      - ./craft/.env.dev:/var/www/site/craft/.env
  redis:
    image: "redis:4.0.10-alpine"
    ports:
      - "6379:6379"
  php:
    build:
      context: ./
      dockerfile: ./docker/development/config/php.dockerfile
    environment:
      - SESSION_SAVE_PATH=redis:6379
    ports:
      - "9000:9000"
    user: php-fpm
    volumes_from:
      - appdata
    tmpfs:
      - /tmp:exec,mode=777
    networks:
      - default
    volumes:
      - ./docker/logs/php:/var/logs/php/
    links:
      - redis
      - mysql
      - vite
  nginx:
    build:
      context: ./
      dockerfile: ./docker/development/config/nginx.dockerfile
    volumes_from:
      - appdata
    tmpfs:
      - /tmp:exec,mode=777
      - /var/cache:exec,mode=777
    ports:
      - "80:80"
    depends_on:
      - php
  mysql:
    image: mysql:5.7.27
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
        - MYSQL_DATABASE=db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
        - "3306:3306"
    volumes:
        - ./docker/mysql/logs/:/var/logs/mysql/
        - mysqldata-vite:/var/lib/mysql
  vite:
    build:
      context: ./docker/development/config/
      dockerfile: ./node.dockerfile
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./buildchain:/var/www/site/buildchain
      - ./craft/web:/var/www/site/craft/web
      - ./src:/var/www/site/src
      - ./craft/templates:/var/www/site/craft/templates
volumes:
  mysqldata-vite:
```

Am I correct in assuming that `client.js` should come through automatically? And I shouldn't need to reference it manually in my template?

Forgive me I expect I have missed something really obvious but I cannot see any logic in the ViteService to handle pulling `client.js` through, the only reference seems to be `self::VITE_CLIENT` which is only used to check that the dev server exists as far as I can tell?
